services:
  - type: web
    name: bananera-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run migrate && npm run seed && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bananera-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: ADMIN_USUARIO
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NOMBRE
        value: Administrador
      - key: CORS_ORIGINS
        value: https://platanos-app-e8208.web.app

databases:
  - name: bananera-db
    plan: free
